language: csharp
solution: Reducto.sln
install:
    - nuget restore Reducto.sln
    - nuget install NUnit.Console -Version 3.8.0 -OutputDirectory testrunner
script:
    - xbuild /p:Configuration=Release Reducto.sln
    - mono ./testrunner/NUnit.ConsoleRunner.3.8.0/tools/nunit3-console.exe ./src/Reducto.Tests/bin/Release/Reducto.Tests.dll